# Generated by Django 4.2 on 2023-10-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0002_alter_genders_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
