# Generated by Django 4.2 on 2023-10-16 22:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('genders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(max_length=300)),
                ('release_date', models.DateTimeField()),
                ('image', models.URLField()),
                ('availability', models.CharField(default='Available')),
                ('actors', models.ManyToManyField(to='actors.actors')),
                ('gender', models.ManyToManyField(to='genders.genders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
