# Generated by Django 4.2 on 2023-10-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movie_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='gender',
            new_name='genders',
        ),
    ]
