# Generated by Django 4.2 on 2023-10-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
