# Generated by Django 4.2 on 2023-10-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_gender_movies_genders'),
        ('actors', '0002_alter_actors_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
    ]
